name: Create pull request

on:
  push:
    branches:
      - "feature*"

jobs:
  main: Create pull request
  runs-on: ubuntu-latest

  steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: create pull request
      uses: peter-evans/create-pull-request@v4
