name: Integrate changes

on:
  pull_request:
    types: [opened]

jobs:
  main:
    name: Integrate changes
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: automatic rebase
        uses: cirrus-actions/rebase@1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test via jest
        run: |
          npm install
          npx jest

      - name: extract branch name
        run: echo "##[set-output name=branch;]${GITHUB_HEAD_REF#refs/heads/}"
        id: extract_branch

      - name: merge feature into main
        run: |
          git checkout origin/main
          git merge 'origin/${{ steps.extract_branch.outputs.branch }}'