name: Integrate pull request

on:
  push:
    branches-ignore:
      - main

jobs:
  create-pull-request:
    name: Create pull request
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: create pull request
        uses: repo-sync/pull-request@v2.6.2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}

  integrate-changes:
    name: Integrate changes
    needs: create-pull-request
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: rebase feature branch onto main
        uses: cirrus-actions/rebase@1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: testing
        run: |
          npm install
          npx jest

      - name: merge feature branch into main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
