# name: Integrate changes

# on:
#   pull_request:
#     types: [opened]

# jobs:
#   main:
#     name: Integrate changes
#     runs-on: ubuntu-latest

#     steps:
#       - name: checkout repo
#         uses: actions/checkout@v3
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           fetch-depth: 0

#       - name: rebase feature branch onto main
#         uses: cirrus-actions/rebase@1.7
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - name: testing
#         run: |
#           npm install
#           npx jest

#       - name: merge feature branch into main
#         uses: devmasx/merge-branch@master
#         with:
#           type: now
#           target_branch: main
#           github_token: ${{ secrets.GITHUB_TOKEN }}
