name: Rebase Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  main:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      
      - name: automatic rebase
        uses: cirrus-actions/rebase@1.7
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      - name: remove label
        if: always()
        uses: actions-ecosystem/action-remove-label@v1
        with:
          labels: rebase
